### ISSUE TITLE
Example code not working as expected

### ISSUE THREAD

**Issue by pongchileong** [Infineon/CY8CKIT-028-SENSE#1]
**Prerequisites**

Can you reproduce the problem reliably?
Yes
Did you check current release notes for known issues?
Yes
If this is not the latest release, have you checked newer releases? 
It is latest release
**Description**:
Example code is unable to build as per instructions in link.
Need to add emWIN library and changes to Makefile
**Steps to Reproduce:**
Follow instructions in link.

**Expected Result:**

**Actual Result:**
Failed to build

**Frequency (1/1, 1/50, 1/100):**
NA

**Build/Commit:**
NA
Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

The chip or kit you are working with
CY8cKIT-062S2-43012 + CY8CKIT-028-SENSE
**Host OS and Version:**

MacOS, Windows, Linux
Windows
**Compiler:**
MTB 3.1
Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

Add CY8CKIT-028-SENSE and emWIN library

Add to Makefile
COMPONENTS+=EMWIN_NOSNTS
LDFLAGS+=-u _printf_float

Changes to original main.c
/*******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the Empty Application Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
*
*******************************************************************************
* Copyright 2021-2024, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Header Files
*******************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy8ckit_028_sense.h"
#include "GUI.h"
#include <stdio.h>
/******************************************************************************
* Macros
*******************************************************************************/

/*******************************************************************************
* Global Variables
*******************************************************************************/

/*******************************************************************************
* Function Prototypes
*******************************************************************************/

/*******************************************************************************
* Function Definitions
*******************************************************************************/

/*******************************************************************************
* Function Name: main
*********************************************************************************
* Summary:
* This is the main function for CPU. It...
*    1.
*    2.
*
* Parameters:
*  void
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;
    cyhal_i2c_t i2c_obj;
    char buf[50];
//    xensiv_dps3xx_t pressure_sensor;
    float pressure, temperature;

    cyhal_i2c_cfg_t i2c_cfg = {
        .is_slave = false,
        .address = 0,
        .frequencyhal_hz = 400000
    };

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdt_obj);
#endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();

    /* Board init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize the I2C to use with the OLED display */
    result = cyhal_i2c_init(&i2c_obj, CY8CKIT_028_SENSE_PIN_I2C_SDA, CY8CKIT_028_SENSE_PIN_I2C_SCL, NULL);
    CY_ASSERT(result == CY_RSLT_SUCCESS);

    result = cyhal_i2c_configure(&i2c_obj, &i2c_cfg);
    CY_ASSERT(result == CY_RSLT_SUCCESS);

    xensiv_dps3xx_t* pressure_sensor = cy8ckit_028_sense_get_pressure_sensor();

    /* Initialize pressure sensor */
    //result = cy8ckit_028_sense_init(&i2c_obj, NULL, NULL, NULL, NULL);
    result = xensiv_dps3xx_mtb_init_i2c(pressure_sensor, &i2c_obj, XENSIV_DPS3XX_I2C_ADDR_DEFAULT);
    CY_ASSERT(result == CY_RSLT_SUCCESS);

    //    /* Initialize the OLED display */
    result = mtb_ssd1306_init_i2c(&i2c_obj);
    CY_ASSERT(result == CY_RSLT_SUCCESS);

    /* Enable global interrupts */
    __enable_irq();

    GUI_Init();

    for (;;)
    {
        /* Get the pressure and temperature data and print the results to the OLED display */
        xensiv_dps3xx_read(pressure_sensor, &pressure, &temperature);

//        GUI_DispString("Pressure: %f, Temp: %f", pressure, temperature);
        GUI_GotoXY(0,0);
        sprintf(buf,"Pressure: %4.2f",pressure);
        GUI_DispString(buf);
        GUI_GotoXY(0,10);
        sprintf(buf,"Temp: %2.2f",temperature);
        GUI_DispString(buf);

        cyhal_system_delay_ms(1000);
    }
}

/* [] END OF FILE */

**Comment by Daniyal-Shaikh-15** [comment]
Hey @pongchileong,

Recently there is a release of new version(1.1.0 ) of"CY8CKIT-028-SENSE" library.
I tried recreating your issue from my end, I did not face any build error while recreating.

The following conditions were checked with the code you provided:
	1. We tested using both the 1.0.0 version (old version) and new latest release 1.1.0 version of "CY8CKIT-028-SENSE" library by keeping the latest version(6.32.0) of "emwin" and did not face any build issue.

I would suggest you to retry building your project using the steps mentioned in ["CY8CKIT-028-SENSE shield support library"](https://github.com/Infineon/CY8CKIT-028-SENSE) and also try using the latest version of "CY8CKIT-028-SENSE" and "emwin" library  in your project.

If your build error prevails then please do attach the screenshots of build error or the error log.

Hope this resolves your issue. 

Thanks and Regards,
Daniyal Shaikh

**Comment by pongchileong** [comment]
Hi Daniyal Shaikh,

I tried the new release and example code and it works as expected.

Thanks for following up.

Regards,
Pong Chi Leong
